# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  bootstrap:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install
        run: npm install -f

  test:
    needs: [bootstrap]
    runs-on: ubuntu-18.04
    steps:
      - name: Lint
        run: ./node_modules/.bin/ng lint

      - name: Test
        run: ./node_modules/.bin/ng test --configuration=ci

  build:
    needs: [bootstrap, test]
    runs-on: ubuntu-18.04
    steps:
      - name: Build Angular
        run: ./node_modules/.bin/ng build --prod

      - name: Build Scully
        run: npm run scully

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: static
          path: ./dist/static

  deploy:
    needs: [bootstrap, test, build]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: static
          path: dist

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
